# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Tom's Knowledge Base"
description: Tom Donohue's place for tech summaries and code snippets.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kb.tomd.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: monodot
github_username:  monodot

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-toc
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md

kramdown:
  parse_block_html: true

header_pages:
  - about.md

permalink: /:title:output_ext

collections:
  articles:
    output: true
    permalink: /:title:output_ext

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: page
      toc: true

toc:
  min_level: 2
  max_level: 3
